### ISSUE TITLE
pre-trained weights 

### ISSUE THREAD

**Issue by bkonk** [CPBridge/ct_body_composition#1]
Thank you for posting this code. Do you provide or do you plan to provide pre-trained weights for this? (apologies if its already included and I missed it)

thanks

**Comment by CPBridge** [comment]
Hi. I'm sorry, but we are not planning to fully release the trained weights publicly at this time. If you are interested in potentially collaborating, please email me privately with some more details and we can discuss further (chrisbridge44 at gmail dot com).

**Comment by CPBridge** [comment]
Further information has been added to the readme in #2 . Closing this issue
